### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by sreen020** [cmda-bt/be-course-21-22#1]
# Package

## Name
Sjoerd Reen

## Class
Tech-3

## Repo link
https://github.com/sreen020/blok-tech-2022

## Summary
- Added the setup for socket.io. Log when user connects or disconnects
- Added Nodemon

**Comment by victorboucher** [comment]
Niceee Sjoerd, ben benieuwd wat je met websockets gaat doen. Prima uitvoering van de eerste opdracht.
Succes!
