### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by Mawrengow** [cmda-bt/be-course-21-22#101]
# Package

## Name
Danian Marengo

## Class
Tech ― 3

## Repo link
https://github.com/Marengd/pt-matching-app-21-22

## Summary
In deze week heb ik mij gericht op het genereren van ideeën voor mijn 'matching applicatie', het vaststellen van een concept, het opstellen van job stories en het uitwerken van een requirement list.

## Resources used
https://github.com/cmda-bt/pt-course-21-22/blob/main/slides/bt_kick-off_21-22.pdf
https://github.com/cmda-bt/pt-course-21-22/blob/main/slides/pt_lab-1_21-22.pdf

## Any thoughts?
Was een duidelijk verhaal waarin duidelijk werd gemaakt waar we naartoe zullen werken.

**Comment by victorboucher** [comment]
Hi Danian, je hebt een goede basis staan. Ik zou je aanraden om zo snel mogelijk met de volgende opdrachten aan de slag te gaan, deze zijn uitdagend maar hoe eerder je hiermee begint hoe beter. Dan zal je applicatie ook een stuk meer vorm krijgen. Ga zo door!!
