### ISSUE TITLE
Week 3

### ISSUE THREAD

**Issue by rarooij98** [cmda-bt/be-course-21-22#105]
# Input

## Name
Robin

## Class
tech-1

## Repo link
https://github.com/rarooij98/matching-application

## Summary
Ik heb wat dingen geleerd over http methods zoals get, post, delete. Ik kan nu info uit een form ophalen. Ik heb eerst een test form gemaakt tot ik dat een beetje werkend kreeg. Daarna heb ik dit toegepast op mijn eigen feature door radio buttons met images in een form te zetten en de aangeklikte keuze te sturen naar de console (als dat heel vaag klink kijk even in [mijn repo](https://github.com/rarooij98/matching-application) 😄). Daarna wordt de gebruiker doorgestuurd naar een succespagina waar weer wordt vermeld welke keuze hij heeft gemaakt.
En daarna heb ik geconnect met mongodb en geleerd hoe ik passwords in een .env file kan zetten.

## Resources used
📜  Documentatie body-parser: https://www.npmjs.com/package/body-parser
📜 Documentatie body-parser: https://www.npmjs.com/package/multer
🎥 Video over post requests: https://www.youtube.com/watch?v=rin7gb9kdpk
🎥 Video over dotenv: https://thecodingtrain.com/Courses/data-and-apis/3.4-hiding-api-key.html

## Any thoughts?
Ik vond het ophalen van info uit een form eerst best wel lastig, ik was in de war geraakt doordat ik de documentatie niet goed begreep en het was moeilijk om zelf extra bronnen te vinden die relevant en/of betrouwbaar waren. Ik ben even bij het vragenuurtje langsgegaan en toe snapte ik weer wat ik moest doen.

**Comment by SamSlotemaker** [comment]
Lekker bezig! https://github.com/rarooij98/matching-application/blob/92ddfa889a0109205fa41d0a1a1b4a5073103432/index.js#L27 
hier gaat het denk ik nog fout alleen, je doet eerst een res.render en dan nog een res.redirect, dus je rendert eerst een pagina en daarna wil je hem nog redirecten naar een andere route, dat is niet logisch denk ik!
