### ISSUE TITLE
Week 3

### ISSUE THREAD

**Issue by GittyHoo** [cmda-bt/be-course-21-22#106]
# Input

## Name
Luka Bronius

## Class
Tech 2 - 211

## Repo link
https://github.com/GittyHoo/NewLifePets

## Summary
This week I finally managed to do quite some work with my backend teacher, Janno. He sat down with me and helped me get my code in order. He also helped me with creating a server and connecting that server with my code/website. I was totally blown away by how hard backend and frontend can be in the first few weeks, which made me feel very stressed and demotivated, but because of the help that I got from Janno, I start to feel motivated again. I still don't understand a lot of things, but I'm slowly getting there.

## Resources used
This week I did quite some research as to how to re-create a swiping feature, like in tinder. For this I used the following youtube tutorials: 
- https://www.youtube.com/watch?v=9yLxmbICrTM
- https://www.youtube.com/watch?v=5bxFSOA5JYo&t=157s
- https://www.youtube.com/watch?v=W6NZfCO5SIk, I haven't watched this tutorial yet, but it's a beginner's guide to javascript.
- the following link is also a tutorial I still need to watch: https://www.youtube.com/watch?v=pyySPJeRvSo

## Any thoughts?
I do think that there should be more classes for the people that are really REALLY new to javascript. This is no shade to the teachers, as they really try to make us understand js/html/css, but I'd like to have some more live-coding with very very simple javascript, where they explain (almost) every element and every move. But I guess this is the: self-studying part, which can be hard when you don't even understand what to (re)search.

**Comment by shabier** [comment]
Hi Luka. I'm happy to see you've been working. I understand that there's a need for more live-coding and guidance, but that's part of development; it's primarily self-studying. Don't forget to make use of the channels in MS Teams!
