### ISSUE TITLE
Week 2

### ISSUE THREAD

**Issue by Laserjonge** [cmda-bt/be-course-21-22#109]
# Templating

## Name
Axel de Ruiter

## Class
Tech-1

## Repo link
[https://github.com/Laserjonge/Blok-Tech](https://github.com/cmda-bt/be-course-21-22/issues/85)

## Summary
I experimented with handlebars to learn more about template engines.

## Resources used
[https://youtube.com/playlist?list=PLurIMwd6GdCi3ssXNAcjZ2l5mYaTfYPhf](https://youtube.com/playlist?list=PLurIMwd6GdCi3ssXNAcjZ2l5mYaTfYPhf)

## Any thoughts?
n/a

**Comment by SamSlotemaker** [comment]
Lekker bezig man. Zorg er voor dat je je bestand schoon houdt door variabelen die je niet gebruikt niet te laten staan, de Path en Res variabelen bijvoorbeeld in je app.js. 

Wellicht wordt het vanaf dit punt een idee om je bestand op te delen in meerdere bestanden, zodat app.js niet enorm lang wordt. Is geen vereiste, maar je bent goed op weg dus wellicht een idee!
