### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by Bram-ter** [cmda-bt/be-course-21-22#11]
# Package

## Name
Bram Tersteeg

## Class
 Tech-3

## Repo link
https://github.com/Bram-ter/blok-tech

## Summary
Ik heb weer een refresh gehad op het werken met git en npm. Ik hoorde van klasgenoten dat zij veel problemen hadden met hun github sleutel/pushen werkend krijgen. Ik had hier gelukkig niet zo veel problemen mee, en dit was snel gefixt. Verder had ik heel even problemen met mijn package.json die opeens heel veel node_modules had gedownload. Maar door het even aan Sonja te vragen was dit snel opgelost.

## Resources used
Ik heb vaak gewoon mijn error gegoogled als ik een probleem had. Hierbij hielpen stackoverflow artikelen/vragen mij meestal wel goed.

## Any thoughts?
Ik vond dit huiswerk fijn om mee van start te gaan. Het was dat ik zelf al een keer met npm heb gewerkt, maar door leerlingen zelf een package te laten installeren leren ze zelf de basis denk ik goed beheersen. Zelf gebruik ik de plugin in vscode om een eigen server mee op te zetten best vaak, daarom vond ik het zelf ook wel interessant om zelf een localhost op te zetten.

**Comment by victorboucher** [comment]
Ziet er goed uit Bram! Nice dat je al hebt geëxperimenteerd met het importeren en exporteren tussen bestanden. Je kunt eventueel nog aan de slag gaan met een van de packages die je hebt geïnstalleerd (of een andere). Verder zou je het .DS_Store bestandje even willen verwijderen uit je repo, ik zie dat je hem ondertussen al in je .gitignore bestand hebt toegevoegd. In ieder geval lekker bezig, ga zo door 🥳
