### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by Chelsey-bommer** [cmda-bt/be-course-21-22#137]
# Package

## Name
Chelsey Bommer

## Class
 Tech5 

## Repo link
https://github.com/Chelsey-bommer/Matching-app 

## Summary
 Ik heb de huiswerk opdrachten gemaakt en dat ging prima. Heb nog extra video's gekeken voor wat ik niet begreep.

## Any thoughts?
Het ging prima.

**Comment by SamSlotemaker** [comment]
Hey Chelsey! Was het ook al gelukt om express aan de praat te krijgen en wat tekst terug te krijgen in de browser? Laat het ander vooral even weten wanneer je er niet uitkomt!

**Comment by Chelsey-bommer** [comment]
Hoi,

Ik ben er nu in de vakantie mee bezig en dat lukt! Ik zal het laten weten
als ik nog ergens tegen aanloop



Op za 30 apr. 2022 17:20 schreef SamSlotemaker ***@***.***>:
