### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by stefanradouane** [cmda-bt/be-course-21-22#138]
# Package

## Name
Stefan Radouane

## Class
tech-4

## Repo link
https://github.com/stefanradouane/bloktech-individueel

## Summary
Ik heb geleerd wat node.js is en hoe je dit moet starten. Ik heb geleerd hoe je git moet installeren en hoe je bestanden makkelijk kan uploaden en commiten. Daarnaast heb ik ook geleerd hoe je met NPM bestanden moet installeren. Hoe ik dit verder allemaal nog moet toepassen en gebruiken

## Resources used
Ik heb de resources gebruikt die op github staan. Daarnaast heb ik een video gekeken op youtube hoe je bestanden kan overzetten via git. https://www.youtube.com/watch?v=LITy_6FoY-w

## Any thoughts?
Ik vond de resources die op github staan vrij ingewikkeld. De video vond ik daarnaast wel heel erg overzichtelijk

**Comment by Chazzers** [comment]
Hi, leuk concept! Ik zie dat je node_modules zijn geupload naar Github, probeer deze aan de hand van de .gitignore file er uit te krijgen. Wees niet bang om vragen te stellen als je ergens tegen aan loopt. Het lijkt er verder op dat je veel probeert en goed bezig bent dus ga vooral zo door! Succes!
