### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by JonnaVisser** [cmda-bt/be-course-21-22#139]
# Package

## Name
Jonna Visser

## Class
Tech-5

## Repo link
https://github.com/JonnaVisser/MatchingApp-Dogs-At-The-Park 

## Summary
In de folder backend in mijn repository staan de oefeningen die ik in de les heb gemaakt. Omdat ik in blok 3 project tech ben begonnen maar nu weer verder ga heb ik al wat dingen af. Om toch per week nog alles een keer door te nemen en te kijken of ik deze periode alles heb begrijp hou ik per week bij welke stof van belang is. Dit houd ik bij in mijn wiki. voor deze week heb ik bij  week 1 back-end de belangrijke punten toegevoegd.

## Resources used
[npm](https://www.npmjs.com/)

**Comment by SamSlotemaker** [comment]
Top dat je het in ieder geval bij houdt ookal heb je het al af. Schroom vooral niet om om hulp te vragen als iets nog niet helemaal duidelijk is!
