### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by AllyssaA** [cmda-bt/be-course-21-22#140]
# Package

## Name
Allyssa Alimoestar

## Class
Tech-4

## Repo link
https://github.com/AllyssaA/matching-app2

## Summary

- setup boilerplate 
- setup express to run server locally 
- installed npm packages

## Resources used

My previous projects, documentation of NPM and their packages.

## Any thoughts?

All good so far.

**Comment by Chazzers** [comment]
Hi, ziet er tot nu toe goed uit! Vet dat je al bezig bent met partials en die includen in je views. Ik raad aan om ook alvast wat dingen te documenteren over je project en concept in je README. Je bent verder lekker bezig en ga vooral zo door!
