### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by rvdegroen** [cmda-bt/be-course-21-22#142]
# Package

## Name
roshnie de groen

## Class
TECH5

## Repo link
https://github.com/rvdegroen/Tech

## Summary
- slides van de les opnieuw gevolgd 
- huiswerk gedaan 

## Resources used
die vanuit gitbub (cmba-bt), npm, google (stackoverflow) 

## Any thoughts?
Met veel bloed zweet en tranen is het me gelukt en ben ik helemaal bij. Ik weet alleen niet welke packs ik zou willen voor mn feature, het kiezen en zoeken vind ik lastig.

**Comment by SamSlotemaker** [comment]
eyy ziet er goed uit! Het kiezen van de exacte package hoeft uiteraard ook niet direct nu al, die kom je vanzelf tegen wanneer je ze nodig gaat hebben. Aarzel ook vooral niet om me een berichtje te schieten als je ergens niet uit komt!
