### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by CYHvA** [cmda-bt/be-course-21-22#143]
# Package

## Name
Chunyin Lai

## Class
Tech 4

## Repo link
https://github.com/CYHvA/Blok-Tech-Individueel

## Summary
Een localserver opgezet vanuit Express waarbij je met Localhost:3000 een "Hello World" pagina krijgt.

## Resources used
Met medestudenten op school en internet

## Any thoughts?
De huidige opdracht is niet perse moeilijk. Maar de vertaling wat de opdracht exact is, is erg verwarrend voor een beginnende student. Er is veel heel informatie in 1 keer waarbij men een slecht beeld krijgen wat het precies inhoud omdat het alle kanten op gaat.

**Comment by Chazzers** [comment]
Hi, gaaf concept! Ik zie verder nog niks staan in je server.js, maar krijg wel het idee aan de hand van je summary dat je het al heb gedaan. Probeer vaak, ook kleine veranderingen, te committen. Dan kun je als er op een gegeven moment iets kapot gaat, terug gaan naar een versie dat nog werkte. Als je verder vragen heb of ergens niet uitkomt, kun je altijd om hulp vragen. Succes!
