### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by sanotje** [cmda-bt/be-course-21-22#145]
# Package

## Name
Sanae Akhiat

## Class
Tech5

## Repo link
https://github.com/sanotje/be/tree/master

## Summary
Ik liep een beetje achter dus ben voor meer duidelijkheid als het ware opnieuw begonnen. Ik heb een git rep gemaakt op mijn laptop met onder andere de server.js erin met package.json en een .gitignore bestand. Ik heb veel uitleg gezocht en gevonden online over npm en hoe dit werkt. Ik heb gekeken naar verschillende packages en het huiswerk gemaakt.
## Resources used
Slides en aantekeningen bekeken, forums gelezen en YouTube filmpjes opgezocht en bekeken.

## Any thoughts?
Let us know what you thought of the homework, and give us any feedback. What parts did you find difficult?

**Comment by SamSlotemaker** [comment]
Goed beginnetje, de basis staat! :D 
Kijk nog eventjes goed naar de dependency's in de package.json, alles dat je niet gebruikt hoeft daar niet in te staan, dat zou er namelijk alleenmaar voor zorgen dat mensen onnodige dingen installeren.
