### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by Neinno** [cmda-bt/be-course-21-22#146]
# Package

## Name
Nigel Fijnheer

## Class
Tech 4

## Repo link
https://github.com/Neinno/Blok-tech

## Summary
Werk van de les gemaakt. Gestart met node en een package aangemaakt. Server.js werkend gekregen.

## Resources used
Github repo, sildes en de informatie die in de les gegeven werd.

## Any thoughts?
Was duidelijk wat er gedaan moest worden. Was wel lastig om te begrijpen in het begin hoe alles werkt.

**Comment by Chazzers** [comment]
Hi, ziet er goed uit! Als je nog vragen heb over iets, wees niet bang ze te stellen! Succes!
