### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by Nowyme** [cmda-bt/be-course-21-22#148]
# Package

## Name
Nowy Meepho

## Class
tech-5

## Repo link
https://github.com/Nowyme/BlockTechgenius

## Summary
Ik heb nodemon, express, lodash en camelcase geïnstalleerd en uitgetest. Daarnaast ook verschillende videos gekeken en tutorials volgen van verschillende package.

## Resources used
- https://lodash.com/docs/4.17.15
- https://www.npmjs.com/
- Github van cmda-bt/be

## Any thoughts?
Het is te doen

**Comment by SamSlotemaker** [comment]
Lekker bezig, het beginnetje staat. Laat het vooral weten wanneer je ergens niet uit komt!
