### ISSUE TITLE
Week 2

### ISSUE THREAD

**Issue by hicham-sahla** [cmda-bt/be-course-21-22#149]
# Templating

## Name
Hicham
## Class
Tech 4
## Repo link
https://github.com/hicham-sahla/blok-tech-feature
## Summary
Ik heb deze week voornamelijk onderzoek gedaan naar EJS en hoe Routing en variabelen doorgeven werkt. Ook heb ik een bestands structuur gemaakt die het makkelijker maakt om bestanden te hergebruiken.  EJS heb ik geinstalleerd.
## Resources used

https://www.digitalocean.com/community/tutorials/how-to-use-ejs-to-template-your-node-application
## Any thoughts?
Gaat wel lekker. Project begint nu een beetje vaart te krijgen.

**Comment by Chazzers** [comment]
Hey, ik zie dat je al lekker op weg bent! Ik kom wel een beetje html tegen in je README.md. Ik raad aan om nog even te kijken naar markdown en je readme op deze manier te schrijven https://www.markdownguide.org/cheat-sheet/. Als je verder nog vragen heb, stel ze gerust! Succes!
