### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by YaraPrins** [cmda-bt/be-course-21-22#15]
# Package

## Name
Yara Prins

## Class
Tech 3

## Repo link
https://github.com/YaraPrins/blok-tech.git

## Summary
I made some subfolders in this repo for all of my classes, and in my project tech folder I put another subfolder for my research.
I also made a .gitignore , README.md , added a licence (MIT), and made some different pages to my wiki.
I also put my folder where I put my json packages and helloworld.js , in my BackEnd subfolder (it's called Matching App)

## Resources used
GitHub repo from PT, BE + the given resources from the assignments.
I also asked Bram a bit for help, since he was finished sooner than me.
Oh, and myself of course, I used just lots of trial and error.

## Any thoughts?
Maybe a bit more explanation for Windows users, & how to set up a server (I had to look really hard to find the resource for it, but I'd rather had some in class demo's or something

**Comment by victorboucher** [comment]
Lekker bezig Yara! Je hebt de opdracht(en) goed uitgevoerd en nice dat je al een beetje hebt gespeeld met template literals. Ik zou je wel aanraden om je repo zo opgeruimd mogelijk te houden, en dus bestandjes als 'test.txt' die leeg zijn te verwijderen. Ga zo door!
