### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by Thogronen** [cmda-bt/be-course-21-22#150]
# Package

## Name
Thomas Groeneweg

## Class
Tech-4

## Repo link
(https://github.com/Thogronen/plant-lf-room/tree/BD-W1)

## Summary
Added package.js and server.js

## Resources used
https://www.npmjs.com/
https://www.w3schools.com/js/js_variables.asp
https://docs.github.com/en/get-started/quickstart/hello-world
https://www.freecodecamp.org/news/git-switch-branch/
https://expressjs.com/en/starter/hello-world.html

## Any thoughts?
Er een week niet zijn maakt het begin wel extra moeilijk. :) Had wat probleempjes met Git - er was een map die niet opgehaald wilde worden.

**Comment by Chazzers** [comment]
Hey, rot om te horen dat je een week heb gemist. Als je ergens tegen aan loopt of iets niet begrijpt, wees niet bang om aan mij, de docent of bij een van je klasgenoten om hulp te vragen. Success!
