### ISSUE TITLE
Week 2

### ISSUE THREAD

**Issue by HanArchives** [cmda-bt/be-course-21-22#151]
# Templating

## Name
Han Ossef

## Class
Tech 5

## Repo link
https://github.com/HanArchives/bloktech

## Summary
Ik ben begonnen met html/css/js. Ook heb ik components en partials gemaakt en die kunnen includen. 

## Resources used
[EJS](https://www.digitalocean.com/community/tutorials/how-to-use-ejs-to-template-your-node-application)

## Any thoughts?
Ik heb nog een beetje moeite met het begrijpen van de Mixins en Conditionals. Zou daar nog wat meer uitleg over willen.

**Comment by SamSlotemaker** [comment]
Ziet er goed uit man. Pagina's al netjes opgedeeld in wat componenten enzo, gaat al de goede kant op! Schroom vooral niet om me een berichtje te sturen op teams als iets nog niet helemaal duidelijk is of als je ergens over wilt sparren.
