### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by samvekemans** [cmda-bt/be-course-21-22#153]
# Package

## Name
Sam Vekemans

## Class
Tech-4

## Repo link
https://github.com/samvekemans/project-tech

## Summary

Ik heb een node project aangemaakt en heb een twee packages geïnstalleerd, ik heb nodemon en express geïnstalleerd.

## Resources used
https://www.npmjs.com/
Github van back-end

## Any thoughts?
Ik vond het best wel goed te doen

**Comment by Chazzers** [comment]
Hey, het ziet er al goed uit! Wat wel opviel was dat de MIT License text in je README.md stond. Ik zou dit verplaatsen naar een LICENSE file in je repository. Laat verder even weten als je vragen heb of ergens niet uitkomt. Keep it up!
