### ISSUE TITLE
Week 2

### ISSUE THREAD

**Issue by Chelsey-bommer** [cmda-bt/be-course-21-22#154]
# Templating

## Name
Chelsey Bommer

## Class
Tech 5

## Repo link
https://github.com/Chelsey-bommer/Matching-app

## Summary
Ik heb het huiswerk gedaan. Ik heb nu een basis html/css pagina opgezet met de routes en partials. Deze is nog niet af maar dit ligt meer aan de front-end kant. 

## Resources used
Mijn gebruikte resources staan bij de artikelen in mijn wiki.

## Any thoughts?
Ik kon eerst niet goed vinden wat mixins waren, maar na een paar dagen heb ik het toch gevonden en begrijp ik het nu

**Comment by SamSlotemaker** [comment]
Lekker bezig hoor. Kijk nog eventjes naar hoe je de partials indeelt. Je `<footer>` is nu namelijk dubbel, je zet hem in de pagina en ook in de partial namelijk. Maak een keuze welke van de 2 jij het meest logisch vindt.
