### ISSUE TITLE
Week 2

### ISSUE THREAD

**Issue by judithkoelewijn** [cmda-bt/be-course-21-22#155]
## Class
Tech-4

## Repo link
https://github.com/judithkoelewijn/matching-2

## Summary
- 4 nieuwe routes aangemaakt en getest
- Eigen 404 pagina gemaakt met error route 
- Serve static files geprobeerd, css en images toegevoegd in public directory

- Research gedaan naar template engines (EJS gekozen)
- Views gemaakt, pagina's gerenderd met verschillende routes
- Includes en conditionals gemaakt en gebruikt, partials toegevoegd (header en footer)
- Framework voor home route gemaakt, header en footer als partials gebouwd en formulier opgezet 

## Any thoughts?
Duidelijke uitleg, ging goed.

**Comment by Chazzers** [comment]
Ziet er goed uit en blijf zo doorgaan! Als je nog ergens tegen aan loopt, kun je hulp vragen aan mij of de andere assistent.

**Comment by judithkoelewijn** [comment]
Thanks!
