### ISSUE TITLE
Week 2

### ISSUE THREAD

**Issue by rvdegroen** [cmda-bt/be-course-21-22#156]
# Templating

## Name
Roshnie de Groen

## Class
Tech5

## Repo link
https://github.com/rvdegroen/Tech

## Summary
Ik heb veel gekeken hoe ik ejs moet gebruiken en snap het meer, Zit te twijfelen of ik met m'n css nu ga beginnen of op het eind, aangezien ik het idee heb dat ik hierop minder word beoordeelt. 

## Resources used
https://ejs.co/

## Any thoughts?
Ik moest mixins googlen omdat ik het niet snapte. Ik ben echt niet blij met mijn code en wil opnieuw beginnen (ik heb bijna niks dus kan makkelijk)

**Comment by SamSlotemaker** [comment]
Opzich ziet het er netjes uit. Maak even de overweging of het nodig zou zijn om helemaal opnieuw te beginnen of gewoon wat stukjes code te refactoren bijvoorbeeld. Laat het vooral weten wanneer je ergens niet uit komt, want je bent op de goede weg!
