### ISSUE TITLE
Week 2

### ISSUE THREAD

**Issue by Mennovlaming** [cmda-bt/be-course-21-22#157]
# Templating

## Name
Menno Vlaming

## Class
Tech-4 

## Repo link
https://github.com/Mennovlaming/blok-tech 

## Summary
Matchapp om reizigers aan elkaar te koppelen, gebruikers kunnen elkaar opzoeken om bijvoorbeeld samen met de bus naar een festival te gaan, een gebruiker kan een bestemming toevoegen en zoeken of een reis al bestaat.

**Comment by SamSlotemaker** [comment]
yoyo hij is leeg

**Comment by Chazzers** [comment]
Hey Menno, ik zie in je repo staan dat je nog node_modules mee commit naar github. Probeer dit op te lossen aan de hand van een .gitignore file. Verder zie ik dat je al een aantal routes heb aangemaakt dus een basis heb je al staan. Ik kan verder niet goed aflezen hoe ver je bent, maar probeer in ieder geval bij te blijven en als je vragen heb, stel ze op tijd! Success!
