### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by svendoejaaren** [cmda-bt/be-course-21-22#16]
# Package

## Name
Sven Doejaaren

## Class
Tech-1

## Repo link
https://github.com/svendoejaaren/blok-tech

## Summary
- Begonnen met nodejs door middel van de terminal
- 2 Javascript bestanden gemaakt om geïnstalleerde npm packages uit te proberen (match-sorter en nodemon)
- 'Hello World' opdracht gemaakt
- Applicatie start door middel van terminal (running script)

## Resources used
npm:
- https://www.npmjs.com/package/match-sorter
- https://docs.npmjs.com/cli/v8/using-npm/scripts

nodemon:
https://nodemon.io/

Hello World voorbeeld:
- https://expressjs.com/en/starter/hello-world.html

## Any thoughts?
Ik vond het huiswerk best lastig. Tijdens de les stonden de slides nog niet op github dus ik kon niet terugkijken hoe alles moest. Er was ook nog veel onduidelijk, zoals wat een boilerplate is en hoe je een npm package moet testen, maar dat is duidelijker geworden door Robert en Stein. Desondanks kijk ik uit naar de tweede les.

**Comment by SamSlotemaker** [comment]
Lekker bezig Sven, fijn dat het uiteindelijk wat duidelijker is geworden. Aarzel ook vooral niet om mij of Stein buiten de lessen om een berichtje op teams te schieten. Misschien dat je er wel uitkomt maar dat bepaalde dingen toch nog niet helemaal duidelijk zijn of dat je eigenlijk niet precies weet hoe het werkt, dan kunnen we wellicht nog wat meer duidelijkheid bieden! 

Verder vooral zo door gaan!
