### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by ninadepina** [cmda-bt/be-course-21-22#17]
# Package

## Name
Nina Vens

## Class
tech-2

## Repo link
https://github.com/ninadepina/bloktech

## Summary
Vertrouwd raken met het werken in de terminal en de basis van npm.

## Resources used
- VS code
- terminal
- https://www.npmjs.com

## Any thoughts?
ʕ ᵔᴥᵔ ʔ  <-- een koala

**Comment by shabier** [comment]
Hi Nina, ik zie dat je aardig op weg bent. Lekker bezig, keep it up!
