### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by rarooij98** [cmda-bt/be-course-21-22#18]
# Package

## Name
Robin van Rooij

## Class
Tech-1

## Repo link
https://github.com/rarooij98/matching-application

## Summary
Ik heb geleerd wat NPM is en hoe ik het kan gebruiken.

## Resources used
De live demo video over npm vond ik een heel handige resource. Ik begreep er namelijk helemaal niks van tot ik die video vond (https://www.youtube.com/watch?v=shSB9BbK1gU).

## Any thoughts?
Het is gelukt om alle opdrachten uit te voeren door de stappen te volgen, maar ik weet niet of ik 100% begrijp _waarom_ het werkt. Hopelijk ga ik daar komende weken nog iets meer achter komen.

**Comment by SamSlotemaker** [comment]
Hey robin! Lekker bezig, het begin staat :) 
Voel je vrij om me even een berichtje op teams te sturen als je nog niet helemaal 100% begrijp _hoe_ en _waarom_ het werkt. Niks is namelijk zo vervelend de basis niet onder de knie te hebben!
