### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by TeunvK** [cmda-bt/be-course-21-22#2]
# Package

## Name
Teun van Kessel

## Class
Tech-1 

## Repo link
https://github.com/TeunvK/BlokTech

## Summary
Created a boilerplate, added gitignore, added a start run script and server.
Added the dependencies:
- Camelcase
- nodemon

## Resources used
https://www.npmjs.com/package/camelcase
https://nodemon.io/
https://docs.npmjs.com/cli/v8/using-npm/scripts#npm-start

**Comment by SamSlotemaker** [comment]
Niks mis mee :)
