### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by Romy-Thu** [cmda-bt/be-course-21-22#20]
# Package

## Name
Romy-thu Zwijnenburg

## Class
Tech-2

## Repo link
https://github.com/Romy-Thu/Blok-Tech_klas-tech2

## Summary
Voor back-end heb ik geprobeerd om verschillende packages te instaleren, zoals modemon ...
Verder heb ik ook geprobeerd om mijn werk te pushen zodat het up to date blijft.  Ook heb ik met janno geprobeerd om de wiki template toe tevoegen, maar hellaas geen succes. Verder heb ik geprobeerd om te begrijpen wat alles inhoud en alles te verwerken (nog mee bezig)

## Resources used
https://changelog.com/posts/install-node-js-with-homebrew-on-os-x
& Janno aka detechdocent 

## Any thoughts?
Dit vak is erg pittig en nu zo na de eerste les, ben ik bang of ik het wel ga halen en of ik alles wel goed inlever. Want dit is nog erg vaag

**Comment by shabier** [comment]
Hi Romy! Geen paniek, ik zie dat je goed je best doet- zo kom je er wel. Vergeet je niet aan de bel te trekken bij de assistenten als je ergens niet uit komt? Keep it up!
