### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by markschuttehva** [cmda-bt/be-course-21-22#27]
# Package
Express?

## Name
Mark Schutte

## Class
Tech 2

## Repo link
https://github.com/markschuttehva/back-end-tech-21-22

## Summary
Setting up the backend, installing npm packages

## Resources used
School resourses, npm package list

## Any thoughts?
Was quite difficult to do but I think I worked somehow.

**Comment by shabier** [comment]
Hi Mark. Ik zie nog geen bestanden in je repo, vergeet je deze niet te committen?
