### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by Sanne1998HvA** [cmda-bt/be-course-21-22#3]
# Package

## Name
Sanne Kes

## Class
Tech 1

## Repo link
https://github.com/Sanne1998HvA/ProjectTech)

## Summary
Ik heb deze week een boilerplate gemaakt, camelcase en na homebrew gedownload te hebben nodemon gedownload, een .gitignore toegevoegd zodat de grootste bestanden niet naar GitHub worden gestuurd en express gedownload.

## Resources used
https://www.npmjs.com/package/camelcase
https://www.npmjs.com/package/nodemon
https://docs.npmjs.com/cli/v7/commands/npm-start
En heb hulp gekregen met homebrew downloaden van Janno omdat ik iets niet kon downloaden.

## Any thoughts?
Ik vind het wel moeilijk maar met een beetje hulp kom ik al heel ver. Ik ben op schema tot nu dus ben happy.
Begin het te snappen! :)

**Comment by SamSlotemaker** [comment]
Lekker bezig, de fundering staat :D 
Het begin is inderdaad even zoeken, maar als je gewoon op schema blijft dan komt het zeker goed!

**Comment by Sanne1998HvA** [comment]
Jaa precies, moet vooral dit keer bijblijven elke week. Dat is het belangrijkste. Daar ging het vorige keer vooral mis. (ben een herkanser)
