### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by MichaelWilhelm1** [cmda-bt/be-course-21-22#30]
# Package

## Name
Michael Wilhelm

## Class
Tech-3

## Repo link
https://github.com/MichaelWilhelm1/Tech-Blok

## Summary
Ik heb de Package en Serve opdracht gedaan. Camelcase geïnstalleerd en gebruikt via npmjs.com

## Resources used
De uitleg video's, npmjs.com en een site met uitleg over serve.

## Any thoughts?
Was wel te doen, maar om voor de eerste keer te doen was het wel een uitzoekerij.

**Comment by Martin803** [comment]
Heel mooi

**Comment by MichaelWilhelm1** [comment]
thanks ouwe
