### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by bladennis** [cmda-bt/be-course-21-22#33]
# Package

## Name
Dennis de Graaf

## Class
Klas 1

## Repo link
[https://github.com/DennisHvA/Blok-tech](https://github.com/DennisHvA/Blok-tech)

## Summary
Ik heb NPM geïnstalleerd en hiermee heb ik de packages: camelcase, nodemon en express geïnstalleerd. Nodemon heb ik als dev dependencies geïnstalleerd. Ook heb ik een script aangemaakt. Het is mij alleen nog niet gelukt om de bestanden via Git in mijn repository op GitHub te zetten. Ik loop vast met mijn personal acces token. 

## Resources used
Studentassistent

## Any thoughts?
Het is fijn dat we nog niet meteen opdrachten kregen, want het is nu nog steeds lastig om alles geïnstalleerd te hebben.

**Comment by SamSlotemaker** [comment]
yo yo Dennis, ik zie dat het inmiddels gelukt is je bestanden te pushen? Dat is in ieder geval lekker :D 

Probeer ook eens te kijken of je de server met express al kan creëren en opstarten, [dit verhaaltje](https://github.com/cmda-bt/be-course-21-22/blob/main/week-1.md#serve)
