### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by robin500818167** [cmda-bt/be-course-21-22#5]
# Package

## Name
Robin van Houten

## Class
Tech 1

## Repo link
[Mijn link](https://github.com/robin500818167/Project-Tech)

## Summary
De opdrachten van Week 1 Package en server.

## Resources used
Google

## Any thoughts?
Goed te doen veel uitzoeken op Google, maar daarmee kom je een end.

**Comment by SamSlotemaker** [comment]
Lekker bezig, het begin staat! 
Wellicht mooi om een variabele te maken van de poort waarop je applicatie runt, in plaats van deze in de functie te zetten, houdt het wellicht wat overzichtelijker! 

En ga je onderscheid maken tussen server.js en index.js?
