### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by yelizerbas** [cmda-bt/be-course-21-22#52]
# Package

## Name
Yeliz

## Class
tech-2

## Repo link
https://github.com/yelizerbas/blok-tech

## Summary
Ik heb al het huiswerk gedaan voor deze week. Alles is (als het goed is) helemaal in orde. Ik heb nog nooit met de terminal gewerkt, dus het was erg nieuw voor mij. Ik vond het wel irritant dat ik tegen dingen aan liep, maar ergens ook leuk want dan weet je dat je dingen gaat leren en er beter in gaat worden naarmate de tijd.

## Resources used
De dingen die ik gebruikt heb zijn natuurlijk de stappenplannen. Ook hebben klasgenoten mij heel erg geholpen.

## Any thoughts?
Ik vond sommige dingen installeren met de terminal best lastig, omdat het niet werkte bij mij. Gelukkig is dat allemaal opgelost en heb ik al het huiswerk kunnen maken. Het enige waar ik net nog tegen aan loop is het pushen van mijn wiki, dus heb ik het maar handmatig gedaan. Daar hoop ik volgende les wat hulp bij te kunnen krijgen zodat ik daar geen last meer van heb.

**Comment by shabier** [comment]
Hi Yeliz, lekker bezig! Goed om te horen dat je de terminal aan het ontdekken bent. Het is nog altijd handig om cheatsheets erbij te houden zodat je nieuwe dingen kan proberen of als je iets even vergeten bent. Ik zie in je repo dat je handmatig bestanden geüpload hebt, zonde! Trek je wel aan de bel als git niet wilt lukken?
