### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by Laurens256** [cmda-bt/be-course-21-22#54]
# Package

## Name
Laurens Duin

## Class
tech-2

## Repo link
https://github.com/Laurens256/bloktech

## Summary
Ik ben eerste begonnen met de huiswerkopdracht. Toen ik die af had ben ik wat verder gegaan met de feature die ik wil maken.

## Resources used
Socket.io documentatie, mongodb documentatie/starters guide

**Comment by shabier** [comment]
HI Laurens. Ik zie dat je al begonnen bent met Socket.io, sick! Vergeet je de comments niet uit je code te halen? Tip: je kan een variable loggen als `console.log({variable})` dan hoef je niet een extra string ervoor te typen :p
