### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by MegandeRuig** [cmda-bt/be-course-21-22#56]
# Package

## Name
Megan de Ruig

## Class
Tech 2

## Repo link
https://github.com/MegandeRuig/Project-Tech

## Summary
Ik heb de eerste opdracht gemaakt en hierbij verschillende npm packages geinstalleerd (camelcase).  Verder ben ik vervolgens door gegaan naar de 2e assignment en is het mij na een beetje research gelukt om hello world te laten verschijnen in de local host.

## Resources used
Local host opdracht: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/Introduction

## Any thoughts?
Ik had in het begin wat moeite met het begrijpen van de opdrachten maar na het kijken van de video's kwam ik er aardig doorheen.

**Comment by shabier** [comment]
Hi Megan, goed om te horen dat het goed gaat. Vergeet je niet lege bestanden uit je repo te halen, dat staat namelijk netter!
