### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by annekesteller** [cmda-bt/be-course-21-22#57]
# Package

## Name
Anneke Steller

## Class
tech2

## Repo link
https://github.com/annekesteller/bloktech

## Summary
Ik heb het huiswerk van deze week af kunnen maken. Ik moet wel zeggen dat ik er nog steeds weinig van begrijp maar ik hoop dat dat de komende weken zal verbeteren. 

## Resources used
https://expressjs.com/en/starter/hello-world.html

## Any thoughts?
Ik vond de uitleg van de theorie en het huiswerk nog best onduidelijk en te moeilijk om te begrijpen voor de eerst week.

**Comment by shabier** [comment]
Hi Anneke. Dat is begrijpelijk, het is vrij lastige stof. Ik denk dat je na een paar oefeningen het vanzelf gaat begrijpen! Vergeet je niet aan de bel te trekken bij de assistenten als je ergens vast zit?
