### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by saskiapool** [cmda-bt/be-course-21-22#63]
# Package

## Name
Saskia 

## Class
Tech-1

## Repo link
(https://github.com/saskiapool/herkansingBackend)

## Summary
Ik heb een package.json file aangemaakt via de command line en daar een paar pakketjes in gezet ook via de command line. Daarna heb ik een server gemaakt in een server.js file en "hello world" komt tevoorschijn als ik die open. Het lukt me alleen nog niet om mijn bestanden in mijn repo te pushen. 

## Resources used
Youtube tutorials, google en de les.

## Any thoughts?
Ik krijg een foutmelding als ik vanuit mijn terminal mijn project wil pushen naar mijn repo.. Ik kom hier zelf niet uit.

**Comment by SamSlotemaker** [comment]
Heyhey, welke foutmelding krijg je? Vraag anders even om hulp in teams!
