### ISSUE TITLE
Week 2

### ISSUE THREAD

**Issue by MichaelWilhelm1** [cmda-bt/be-course-21-22#64]
# Templating

## Name
Michael Wilhelm

## Class
Tech 3

## Repo link
 https://github.com/MichaelWilhelm1/Tech-Blok 

## Summary
Ik heb EJS geïnstalleerd, hiermee heb ik een profile page gemaakt waar de naam verandert voor de naam die je invult. (lees wiki week2 backend development

## Resources used
tutorials the net ninja

## Any thoughts?
best lastig. Ik weet niet zeker of ik alles heb gedaan dat ik moest doen

**Comment by victorboucher** [comment]
Michael, je hebt een goede basis neergezet en de opdrachten voor zover ik kan zien goed uitgevoerd. Ik zou je aanraden om zsm verder te gaan met de volgende opdrachten, hierdoor zal je applicatie echt veel meer tot leven komen en alles denk ik wat duidelijker worden. Ga vooral zo door!
