### ISSUE TITLE
Week 2

### ISSUE THREAD

**Issue by Martin803** [cmda-bt/be-course-21-22#65]
# Templating

## Name
Martin Schaapherder

## Class
tech 3

## Repo link
https://github.com/Martin803/blok-tech

## Summary
de huiswerk opdrachten

## Resources used
De recources van de opdracht

## Any thoughts?
Vond best moeilijk, snap er vrij weinig van, en ik weet ook niet of ik het nou goed heb gedaan

**Comment by victorboucher** [comment]
Hi Martin, wat je hebt gedaan ziet er prima uit hoor. Het is de basis van het gebruik van node/express/templating engines. Misschien kun je nog wat filmpjes of artikelen opzoeken om beter te begrijpen wat je nou eigenlijk hebt gedaan. Ik denk dat dit ook vanzelf in de loop van de tijd wel duidelijker zal worden. Geef vooral niet op en ga zo door!

**Comment by victorboucher** [comment]
Daarnaast kun je mij natuurlijk ook altijd een berichtje sturen op teams als je vragen hebt!
