### ISSUE TITLE
Week 2

### ISSUE THREAD

**Issue by laibaaac** [cmda-bt/be-course-21-22#73]
# Templating

## Name

Laiba Choudhry

## Class

Tech 3
## Repo link

https://github.com/laibaaac/backend-week2.git 

## Summary

Ik deed mee in de les, verder ga ik morgen het huiswerk afmaken met een paar studenten. 

## Resources used

De resources van de les en be course

## Any thoughts?

Ik vind het nogsteeds heel vaag, ik begrijp het niet......

**Comment by victorboucher** [comment]
Hi Laiba, je repo is nog behoorlijk leeg. Ik zie dat je voor het laatst 22 dagen geleden wat naar github heb gepusht. Is dit de juiste repo? Stuur me vooral een berichtje als er ergens niet uit komt, dan zal ik je helpen. Succes!
