### ISSUE TITLE
Week 2

### ISSUE THREAD

**Issue by MarijnMolenaar** [cmda-bt/be-course-21-22#74]
# Templating

## Name
Marijn Molenaar

## Class
TECH 3

## Repo link
(https://github.com/MarijnMolenaar/ProjectTech.git)

## Summary
PUG geinstalleerd, bootstrap geinstalleerd en een aantal views aangemaakt. 

## Resources used
Github en PUG documentatie

## Any thoughts?
Routes werken nog niet helemaal zoals ik wil, sommige routes werken wel en sommige niet. Waarom dit is ga ik uitzoeken.

**Comment by victorboucher** [comment]
Hi Marijn, goed dat je zo erg bezig bent geweest met experimenteren. Ik zal je wel aanraden om wat meer structuur in je repo te brengen. Je hebt nu heel veel losse bestanden in je root zitten, dit wil je het liefste echt wel in mapjes verdelen. Verder raad ik je aan niet de datum als commit message te gebruiken, maar beschrijvende tekst die duidelijk maakt wat je hebt gedaan. De datum kun je zelf terugvinden bij de commit. Succes verder en stuur me vooral een berichtje als je hulp nodig hebt!
