### ISSUE TITLE
Week 2

### ISSUE THREAD

**Issue by Joosiii** [cmda-bt/be-course-21-22#78]
# Templating

## Name
Joost Verweijen

## Class
Tech-3

## Repo link
https://github.com/Joosiii/BlokTech

## Summary
Een HTML + CSS file gemaakt voor de basis van mijn feature. Verder routes gemaakt en een public folder gemaakt voor static files. Ik heb helaas nog geen tijd gehad om te experimenteren met een templating engine.

## Resources used
https://expressjs.com/en/starter/static-files.html
https://www.geeksforgeeks.org/how-to-add-a-404-error-page-in-the-express/

## Any thoughts?
Alles wat ik gedaan heb verliep vrij soepel, al verwacht ik dat het gebruiken van een template engine wat lastiger zal worden.

**Comment by victorboucher** [comment]
Hi Joost, ik zie dat je ondertussen aan de slag bent gegaan met EJS. Nice dat je verder bent gegaan hiermee. Ziet er goed uit, ga vooral zo door!
