### ISSUE TITLE
Week 2

### ISSUE THREAD

**Issue by TessaFlorance** [cmda-bt/be-course-21-22#80]
# Templating

## Name
Tessa

## Class
Tech 3 

## Repo link
 https://github.com/TessaFlorance/Blok-tech.git

## Summary
ik ben er niet helemaal uit gekomen, ik ga samen met een paar andere er nog even een keer naar kijken 

## Resources used
 de slides

**Comment by victorboucher** [comment]
Hi Tessa, ik zie dat je ondertussen verder bent gegaan hiermee, ziet er goed uit. Stuur me een berichtje als je er niet uit komt, dan kan ik evt even met je meekijken!
Verder zit het .DS_Store bestand nog in je repo, deze staat wel in je .gitignore maar die zal je even moeten verwijderen om ervoor te zorgen dat ie niet meer terug komt.
