### ISSUE TITLE
Week 2

### ISSUE THREAD

**Issue by EvaZ7** [cmda-bt/be-course-21-22#84]
# Templating

## Name
Eva Zaadnoordijk

## Class
tech-1

## Repo link
https://github.com/EvaZ7/Blok-tech

## Summary
De basis van routing kunnen toepassen, verder onderzoek gedaan naar verschillende templating engines en handlebars geïnstalleerd.

## Resources used
Stackabuse.com en Google

## Any thoughts?
De template-engines zijn lastig.

**Comment by SamSlotemaker** [comment]
Hey Eva :) 
Het principe is van templating kan misschien wat overweldigend zijn, maar ik zie dat je het wel aan de praat gekregen hebt! 
Wees vooral niet bang ook om me even een berichtje te sturen op teams als je wat hulp of meer uitleg nodig hebt. 

Wellicht zou het nog een idee zijn om de handlebars bestanden in bijvoorbeeld een /views/  mapje te zetten, dat maakt je repo een stukje overzichtelijker.
