### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by Laserjonge** [cmda-bt/be-course-21-22#85]
# Package

## Name
Axel de Ruiter

## Class
Tech-1

## Repo link
[https://github.com/Laserjonge/Blok-Tech]()

## Summary
I studied theory, watched the video's and have made the hello world assignment.

## Resources used
The theory and I have asked some classmates for help.

## Any thoughts?
This course is in line with project tech.

**Comment by SamSlotemaker** [comment]
Probeer ook nog even naar de [Serve](https://github.com/cmda-bt/be-course-21-22/blob/main/week-1.md#serve) opdracht te kijken van week 1, om de server aan de praat te krijgen!
