### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by TimoW75** [cmda-bt/be-course-21-22#9]
# Package

## Name
 Timo

## Class
Tech 1 

## Repo link
https://github.com/TimoW75/BlockTech

## Summary
 Ik heb een package geïnstaleerd en een index.js gemaakt die deze package test. Ik heb ook een node server aangemaakt door middel van express 

## Resources used
NPM library, Stackoverflow, Robert Spier, Klasgenoten 

## Any thoughts?
Opdrachten waren lastig om mee te beginnen aangezien ik niet helemaal begreep wat er gevraagd werd

**Comment by shabier** [comment]
Lekker op weg Timo! Ik zie dat je de `.vscode` folder op de repo hebt staan. Deze word gebruikt om workspace voorkeuren op te slaan (lees: [workspaces](https://code.visualstudio.com/docs/getstarted/settings)). Het bestandje is nog leeg bij jou, als je deze niet gebruikt zou ik het verwijderen
