### ISSUE TITLE
Week 2

### ISSUE THREAD

**Issue by Laurens256** [cmda-bt/be-course-21-22#94]
# Templating

## Name
Laurens Duin

## Class
Tech-2

## Repo link
https://github.com/Laurens256/bloktech 

## Summary
Handlebars templating engine en de mappenstructuur wat verbeterd. Het is nu een stuk overzichtelijker (als het goed is). Ook al het onderzoek over templating engines gedocumenteerd in de wiki

## Resources used
Documentatie van EJS, Pug en HBS.

**Comment by shabier** [comment]
Hi Laurens. Het ziet er inderdaad beter uit! Vergeet je niet om ook je routes uit de `server.js` te halen?
