### ISSUE TITLE
Week 2

### ISSUE THREAD

**Issue by Romy-Thu** [cmda-bt/be-course-21-22#95]
# Templating

## Name
Romy-thu Zwijnenburg

## Class
Tech 2

## Repo link
https://github.com/Romy-Thu/Blok-Tech_klas-tech2

## Summary
Deze week moesten wij templaten en basis routing

## Resources used
Ik heb shabier gevraagd, onze student assistente & aris & video's gekeken. 

## Any thoughts?
Ik vond dit onderdeel echt super moeilijk en ik ben bang of ik dit onderdeel wel ga redden, ik merk dat ik met dit gedeelte erg veel begeleiding nodig had.

**Comment by Romy-Thu** [comment]
Templating is nog niet gelukt, ik word vanmiddag geholpen

**Comment by Romy-Thu** [comment]
als het goed is, is templating gelukt

**Comment by shabier** [comment]
Lekker bezig Romy, keep it up!
