### ISSUE TITLE
Week 2

### ISSUE THREAD

**Issue by MegandeRuig** [cmda-bt/be-course-21-22#96]
# Templating

## Name
Megan de Ruig

## Class
Tech 2

## Repo link
https://github.com/MegandeRuig/Project-Tech

## Summary
Voor week 2 heb ik de routing opdracht gemaakt, dit ging verder zonder problemen. En vervolgens heb ik Handlebars geinstalleerd als templating engine. Met de voorbeeld files kreeg ik deze meteen werkende toen ik echter mijn eigen templates maakte liep ik tegen wat problemen aan maar na veel zoeken vond ik hier uiteindelijk ook een oplossing voor.

## Resources used
Express handlebars github: https://www.npmjs.com/package/express-handlebars
Handlebars tutorial: https://www.youtube.com/watch?v=erfN7fH7A6s
Handlebars page: https://handlebarsjs.com/

## Any thoughts?
Ik had in het begin wat moeite met het begrijpen hoe de templating engines werken waardoor ik wat langer bezig was met de laatste opdracht maar naar mate ik meer research deed over onder andere handlebars door wat tutorials te kijken en te lezen ect. kwam er een steeds duidelijker beeld.

**Comment by shabier** [comment]
Hi Megan. Goed om te horen dat het nu wat duidelijker is geworden. Pro tip; stop je `<head>` element en alles daarin in een partial, dan kun je het op 1 plek bewerken en wordt het overal tegelijkertijd bijgewerkt.
