### ISSUE TITLE
Week 2

### ISSUE THREAD

**Issue by maxvl3** [cmda-bt/be-course-21-22#97]
# Templating

## Name
Max

## Class
Tech-2

## Repo link
https://github.com/maxvl3/blok-tech

## Summary
Deze week heb ik geleerd hoe je een simpele server met statische en dynamische content kunt maken. Ik was er niet bij in de les voor de vakantie, maar ondanks dat is het me gelukt. Ik moet alleen nog features uittesten van mijn templating engine, hier was ik nog niet aan toe gekomen.

## Resources used
https://www.npmjs.com/package/express-handlebars

## Any thoughts?
Ik had wat moeite met Handlebars installeren en werkend krijgen. Maar dit komt waarschijnlijk omdat ik dat heb gemist in de les.

**Comment by shabier** [comment]
Hi Max. Je hebt het goed ingehaald! Vergeet je niet om verder aan je feature te werken?
