### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by romyjkk** [cmda-bt/be-course-21-22#98]
# Package

## Name
Romy

## Class
Tech-2

## Repo link
https://github.com/romyjkk/bloktech

## Summary
Ik moest opnieuw beginnen een paar weken geleden, ik heb nu weer wat packages gedownload, waaronder express, een local host aangemaakt en mijn map gekoppeld aan mijn github repository.

## Resources used
De docent.

**Comment by shabier** [comment]
Hi Romy, vergeet je niet om hulp te vragen als je ergens vast loopt?
